![Python_logo](https://www.python.org/static/community_logos/python-logo-master-v3-TM.png)


 # **Cortex Game: Round2--Conditional Amount**

Please note that you need to run this notebook 'Round2--Conditional Amount' first, before running the notebook 'Round2--Probability of Giving'.

> Before playing the game, you need to connect to SASPy first.
>
>> If it is your first time, please follow the 4 steps mentioned below!

***
## **Connect to SASPy**

**0- Connect to your Google Drive folder**

In [ ]:
my_folder = "/content/drive/MyDrive/Reto-SAS"

from google.colab import drive
drive.mount('/content/drive')

# Change the following code to set your Drive folder
import os
os.chdir(my_folder)
!pwd

Mounted at /content/drive
/content/drive/MyDrive/Reto-SAS

**1- Make sure that your Python version is 3.3 or higher as well as your Java version is 1.8.0_162 or higher**

In [ ]:
!echo "Python is at" $(which python)
!python --version

Python is at /usr/local/bin/python
Python 3.7.15

In [ ]:
!echo "Java is at" $(which java)
!/usr/bin/java -version

Java is at /usr/bin/java
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu218.04, mixed mode, sharing)

**2- Install SASPy**

In [ ]:
!pip install saspy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting saspy
  Downloading saspy-4.4.1.tar.gz (9.9 MB)
     |████████████████████████████████| 9.9 MB 4.4 MB/s
Building wheels for collected packages: saspy
  Building wheel for saspy (setup.py) ... done
  Created wheel for saspy: filename=saspy-4.4.1-py3-none-any.whl size=9937304 sha256=09f25c1cf6e9469e03f1032cda87fe6166f708e7de21dd743d91afd89a2bbd3f
  Stored in directory: /root/.cache/pip/wheels/0a/f6/ab/f7173c8a824856c66f6fd50194bb8fd3ef93fb4f1824be8d0c
Successfully built saspy
Installing collected packages: saspy
Successfully installed saspy-4.4.1

**3- Create the configuration file "sascfg_personal.py"**
Please, check that your Home Region is correct, you can check it at [ODA-SAS](https://welcome.oda.sas.com/home)

In [ ]:
%%writefile sascfg_personal.py
SAS_config_names=['oda']
oda = {'java' : '/usr/bin/java',
#US Home Region 1
'iomhost' : ['odaws01-usw2.oda.sas.com','odaws02-usw2.oda.sas.com','odaws03-usw2.oda.sas.com','odaws04-usw2.oda.sas.com'],
#US Home Region 2
#'iomhost' : ['odaws01-usw2-2.oda.sas.com','odaws02-usw2-2.oda.sas.com'],
#European Home Region 1
#'iomhost' : ['odaws01-euw1.oda.sas.com','odaws02-euw1.oda.sas.com'],
#Asia Pacific Home Region 1
#'iomhost' : ['odaws01-apse1.oda.sas.com','odaws02-apse1.oda.sas.com'],
#Asia Pacific Home Region 2
#'iomhost' : ['odaws01-apse1-2.oda.sas.com','odaws02-apse1-2.oda.sas.com'],
'iomport' : 8591,
'authkey' : 'oda',
'encoding' : 'utf-8'
}

Overwriting sascfg_personal.py

**4- Create your .authinfo**

If there is no .authinfo file, you can create this

In [ ]:
%%writefile .authinfo
oda user a01283727@tec.mx password Chun?Chun!01R

Overwriting .authinfo

Copy this file to home

In [ ]:
!cp .authinfo ~/.authinfo

**5- Establish Connection (Need to do this step each time you use SASPy)**

In [ ]:
import saspy
sas_session = saspy.SASsession(cfgfile=os.path.join(
    my_folder,"sascfg_personal.py"))
sas_session

Using SAS Config named: oda
SAS Connection established. Subprocess id is 360

Access Method         = IOM
SAS Config name       = oda
SAS Config file       = /content/drive/MyDrive/Reto-SAS/sascfg_personal.py
WORK Path             = /saswork/SAS_work26550001F270_odaws04-usw2.oda.sas.com/SAS_work1E430001F270_odaws04-usw2.oda.sas.com/
SAS Version           = 9.04.01M6P11072018
SASPy Version         = 4.4.1
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = utf-8
Python Encoding value = utf-8
SAS process Pid value = 127600

***
## Connect to Cortex Data Sets

Load Cortex datasets from SAS Studio

In [ ]:
ps = sas_session.submit("""
    libname cortex '~/my_shared_file_links/u39842936/Cortex Data Sets';
    """)
print(ps["LOG"])

5                                                          The SAS System                      Friday, December  2, 2022 12:10:00 AM

24         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg style=HTMLBlue;
24       ! ods graphics on / outputfmt=png;
25
26
27             libname cortex '~/my_shared_file_links/u39842936/Cortex Data Sets';
28
29
30
31         ods html5 (id=saspy_internal) close;ods listing;
32

6                                                          The SAS System                      Friday, December  2, 2022 12:10:00 AM

33

For local Jupyter

In [ ]:
#%%SAS sas_session
#libname cortex '~/my_shared_file_links/u39842936/Cortex Data Sets';

### Transform cloud SAS dataset to Python dataframe (pandas)

> For reference: 

> 1- [Pandas library](https://pandas.pydata.org/docs/user_guide/index.html)

> 2- [sklearn.model_selection for data partition](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html)

In [ ]:
import pandas as pd

#comment: Transform cloud sas dataset to python dataframe(pandas) ==> might take some time.

data1 = sas_session.sasdata2dataframe(
table='hist',
libref='cortex'
)

data2 = sas_session.sasdata2dataframe(
table='target_rd2',
libref='cortex'
)

## Merge the Data

In [16]:
#Step1 Merge the Data
data_merge = pd.merge(data1, data2, on=["ID"],how="right")
data_merge = data_merge.loc[(data_merge['GaveThisYear'] ==1)]
data_merge['Contact'].value_counts()

0.0    110406
1.0     39051
Name: Contact, dtype: int64

## Treating Missing Values

>Please be aware that deleting all missing values can induce a selection bias. 
Some missing values are very informative. For example, when MinGift is missing, it means that the donor never gave in the past 10 years (leading to but excluding last year). Instead of deleting this information, replacing it by 0 is more appropriate!

> A good understanding of the business case and the data can help you come up with more appropriate strategies to deal with missing values.

In [17]:
# In this case, we are replacing MinGift by 0.
# You can do the same for what you think is reasonable for dealing with the other variables.

data_merge[['MinGift']] = data_merge[['MinGift']].fillna(value=0)  

data_merge.sample(5)

,ID,LastName,FirstName,Woman,Age,Salary,Education,City,SeniorList,NbActivities,...,Frequency,Seniority,TotalGift,MinGift,MaxGift,GaveLastYear,AmtLastYear,Contact,GaveThisYear,AmtThisYear
542267,2542268.0,BATES,ROY,0.0,39.0,73300.0,University / College,Suburban,3.0,2.0,...,1.0,3.0,500.0,500.0,500.0,0.0,0.0,0.0,1.0,20.0
877059,2877060.0,STEWART,STACY,1.0,51.0,69400.0,University / College,Suburban,0.0,0.0,...,NaN,NaN,NaN,0.0,NaN,1.0,10.0,1.0,1.0,40.0
564779,2564780.0,GIBSON,BRITTNEY,1.0,56.0,101000.0,University / College,City,6.0,0.0,...,2.0,5.0,30.0,10.0,20.0,1.0,25.0,1.0,1.0,10.0
789791,2789792.0,JU,KAREN,1.0,67.0,56800.0,High School,Downtown,0.0,0.0,...,NaN,NaN,NaN,0.0,NaN,0.0,0.0,1.0,1.0,30.0
553625,2553626.0,WILLIAMS,YVONNE,1.0,32.0,233500.0,University / College,City,3.0,0.0,...,2.0,2.0,1000.0,500.0,500.0,1.0,10.0,0.0,1.0,40.0

In [18]:
import numpy as np

In [19]:
data_merge[['MaxGift']] = data_merge[['MaxGift']].fillna(value= 0)
data_merge[['TotalGift']] = data_merge[['TotalGift']].fillna(value= 0)  

data_merge['MinGift'] = np.where(((data_merge['MinGift']==0) & (data_merge['GaveLastYear']==1)), data_merge['AmtLastYear'], data_merge['MinGift'])
data_merge['MaxGift'] = np.where(((data_merge['MaxGift']==0) & (data_merge['GaveLastYear']==1)), data_merge['AmtLastYear'], data_merge['MaxGift'])
data_merge['TotalGift'] = np.where(((data_merge['TotalGift']==0) & (data_merge['GaveLastYear']==1)), data_merge['AmtLastYear'], data_merge['TotalGift'])

data_merge[['Recency']] = data_merge[['Recency']].fillna(value=20) 

data_merge['Recency'] = np.where(((data_merge['Recency']==20) & (data_merge['GaveLastYear']==1)), 1, data_merge['Recency'])
data_merge['Recency'] = np.where(((data_merge['Recency']==20) & (data_merge['GaveLastYear']==0)), 10, data_merge['Recency'])

data_merge[['Frequency']] = data_merge[['Frequency']].fillna(value=20) 

data_merge['Frequency'] = np.where(((data_merge['Frequency']==20) & (data_merge['GaveLastYear']==1)), 1, data_merge['Frequency'])
data_merge['Frequency'] = np.where(((data_merge['Frequency']==20) & (data_merge['GaveLastYear']==0)), 10, data_merge['Frequency'])

data_merge[['Seniority']] = data_merge[['Seniority']].fillna(value=20) 

data_merge['Seniority'] = np.where(((data_merge['Seniority']==20) & (data_merge['GaveLastYear']==1)), 1, data_merge['Seniority'])
data_merge['Seniority'] = np.where(((data_merge['Seniority']==20) & (data_merge['GaveLastYear']==0)), 10, data_merge['Seniority'])

## New Data

In [74]:
new_data = data_merge

In [75]:
new_data=new_data.join(pd.get_dummies(new_data['City'],prefix="City"),how="inner").copy()

new_data=new_data.join(pd.get_dummies(new_data['Education'],prefix="Education"),how="inner").copy()

new_data['is_vip'] = np.where(((new_data['SeniorList']>0) & (new_data['Frequency']>1) & (new_data['TotalGift']>100)), 1, 0)

new_data['is_active'] = np.where(((new_data['Recency']<4) & ((new_data['Referrals']>0) | (new_data['NbActivities']>0)) & (new_data['GaveLastYear']>0)), 1, 0)

new_data['is_potential'] = np.where(((new_data['Recency'] == 1) & (new_data['GaveLastYear']==1) & (new_data['Frequency']==1)), 1, 0)

new_data['is_new'] = np.where(((new_data['GaveLastYear']==0) & (new_data['Recency']==10) & (new_data['Contact']==1)), 1, 0)

new_data['AvgGift'] = new_data['TotalGift'] / new_data['Frequency']

#new_data['is_potential'] = np.where(((new_data['Frequency']==0) & ((new_data['Referrals']>0) | (new_data['NbActivities']>0))), 1, 0)

## Data Partition

In [76]:
# The code below is an illustration on how to sample data on train and validation samples.
# You could use another library or a built-in function to perform sampling.

from sklearn.model_selection import train_test_split
train, validation = train_test_split(new_data, test_size=0.4,random_state=5678) # you can change the percentage
train.sample(5)

,ID,LastName,FirstName,Woman,Age,Salary,Education,City,SeniorList,NbActivities,...,City_Rural,City_Suburban,Education_Elementary,Education_High School,Education_University / College,is_vip,is_active,is_potential,is_new,AvgGift
549931,2549932.0,HAMBEL,ROGER,0.0,84.0,210300.0,High School,Rural,4.0,0.0,...,1,0,0,1,0,0,0,0,0,0.0
820570,2820571.0,AKINS,CAROL,1.0,24.0,8200.0,University / College,City,4.0,0.0,...,0,0,0,0,1,0,1,1,0,20.0
998660,2998661.0,ROME,WILLIAM,0.0,32.0,41200.0,Elementary,City,0.0,0.0,...,0,0,1,0,0,0,0,0,0,0.0
863534,2863535.0,LOPEZ,LEE,0.0,50.0,62800.0,University / College,Rural,9.0,6.0,...,1,0,0,0,1,1,0,0,0,105.0
119425,2119426.0,CHANG,FOSTER,0.0,63.0,27400.0,Elementary,City,6.0,0.0,...,0,0,1,0,0,0,0,0,1,0.0


## Prebuilt Models

***
### Linear Regression Model


> The [sk-learn library]( https://scikit-learn.org/stable/index.html) offers more advanced models.

In [148]:
from sklearn import linear_model

#comment: it's numpy array
X_train = train[['Contact', 'is_vip', 'is_active', 'is_potential', 'Woman', 'Salary', 'Age', 'NbActivities', 'Referrals', 'Frequency', 'Recency', 'Seniority', 'GaveLastYear', 'AmtLastYear', 'TotalGift', 'MinGift', 'MaxGift', 'AvgGift', 'City_City', 'City_Downtown', 'City_Rural', 'City_Suburban', 'Education_Elementary', 'Education_High School', 'Education_University / College']] 
Y_train = train['AmtThisYear']
X_valid = validation[['Contact', 'is_vip', 'is_active', 'is_potential', 'Woman', 'Salary', 'Age', 'NbActivities', 'Referrals', 'Frequency', 'Recency', 'Seniority', 'GaveLastYear', 'AmtLastYear', 'TotalGift', 'MinGift', 'MaxGift', 'AvgGift', 'City_City', 'City_Downtown', 'City_Rural', 'City_Suburban', 'Education_Elementary', 'Education_High School', 'Education_University / College']] 
Y_valid = validation['AmtThisYear']

regr = linear_model.LinearRegression()

regr.fit(X_train,Y_train)

regr_predict=regr.predict(X_valid)

print(regr_predict)

[ 62.51503759  17.59773267 127.71282721 ...  59.31626644  50.79590579
  59.36368233]

In [149]:
#you can change the criteria

import numpy as np
from sklearn import metrics
#MAE
print(metrics.mean_absolute_error(Y_valid,regr_predict))
#MSE
print(metrics.mean_squared_error(Y_valid,regr_predict))
#RMSE
print(np.sqrt(metrics.mean_squared_error(Y_valid,regr_predict)))

64.13657063191681
53147.48023593018
230.5373727531616

## Regression Tree Model（Py）

In [157]:
from sklearn.tree import DecisionTreeRegressor

X_train = train[['Contact', 'is_vip', 'is_active', 'is_potential', 'Woman', 'Salary', 'Age', 'NbActivities', 'Referrals', 'Frequency', 'Recency', 'Seniority', 'GaveLastYear', 'AmtLastYear', 'TotalGift', 'MinGift', 'MaxGift', 'AvgGift', 'City_City', 'City_Downtown', 'City_Rural', 'City_Suburban', 'Education_Elementary', 'Education_High School', 'Education_University / College']] 
Y_train = train['AmtThisYear']
X_valid = validation[['Contact', 'is_vip', 'is_active', 'is_potential', 'Woman', 'Salary', 'Age', 'NbActivities', 'Referrals', 'Frequency', 'Recency', 'Seniority', 'GaveLastYear', 'AmtLastYear', 'TotalGift', 'MinGift', 'MaxGift', 'AvgGift', 'City_City', 'City_Downtown', 'City_Rural', 'City_Suburban', 'Education_Elementary', 'Education_High School', 'Education_University / College']] 
Y_valid = validation['AmtThisYear']

DT_model = DecisionTreeRegressor(max_depth=3, random_state=42).fit(X_train,Y_train)
DT_predict = DT_model.predict(X_valid) #Predictions on Testing data
print(DT_predict)

[ 57.7379232   37.87001839 133.96602933 ...  60.82203649  59.35248263
  60.82203649]

In [158]:
#you can change the criteria
#MAE
print(metrics.mean_absolute_error(Y_valid,DT_predict))
#MSE
print(metrics.mean_squared_error(Y_valid,DT_predict))
#RMSE
print(np.sqrt(metrics.mean_squared_error(Y_valid,DT_predict)))

63.559980257092974
52848.05539784427
229.88704921731514

### **Other models may also be helpful for this game**

Reference: https://scikit-learn.org/stable/supervised_learning.html

## Scoring New Data

### Prepare data for scoring

In [85]:
data3 = sas_session.sasdata2dataframe(
table='score',
libref='cortex'
)
data4 = sas_session.sasdata2dataframe(
table='score_rd2_contact',
libref='cortex'
)
data5 = sas_session.sasdata2dataframe(
table='score_rd2_nocontact',
libref='cortex'
)

 ### Score new data based on your champion model
 
 Pick your champion model from previous steps and use it to predict next year donations. 
 
 In this case, the linear regression model performed better than the regression tree based on the MSE criteria.

### Predict 'amount given' for members who were contacted

In [160]:
scoring_data_contact = pd.merge(data3, data4, on=["ID"],how="right")

In [161]:
from pandas._config.config import register_option


# Perform the same strategy for handling missing values for the score dataset.
# In this case, we will only replace missing values of the MinGift variable.
 
scoring_data_contact[['MinGift']] = scoring_data_contact[['MinGift']].fillna(value=0)
scoring_data_contact[['MaxGift']] = scoring_data_contact[['MaxGift']].fillna(value=0)
scoring_data_contact[['TotalGift']] = scoring_data_contact[['TotalGift']].fillna(value=0)
scoring_data_contact[['Frequency']] = scoring_data_contact[['Frequency']].fillna(value=20)
scoring_data_contact[['Recency']] = scoring_data_contact[['Recency']].fillna(value=20)  
scoring_data_contact[['Seniority']] = scoring_data_contact[['Seniority']].fillna(value=20)

scoring_data_contact['MinGift'] = np.where(((scoring_data_contact['MinGift']==0) & (scoring_data_contact['GaveLastYear']==1)), scoring_data_contact['AmtLastYear'], scoring_data_contact['MinGift'])
scoring_data_contact['MaxGift'] = np.where(((scoring_data_contact['MaxGift']==0) & (scoring_data_contact['GaveLastYear']==1)), scoring_data_contact['AmtLastYear'], scoring_data_contact['MaxGift'])
scoring_data_contact['TotalGift'] = np.where(((scoring_data_contact['TotalGift']==0) & (scoring_data_contact['GaveLastYear']==1)), scoring_data_contact['AmtLastYear'], scoring_data_contact['TotalGift'])

scoring_data_contact['Recency'] = np.where(((scoring_data_contact['Recency']==20) & (scoring_data_contact['GaveLastYear']==1)), 1, scoring_data_contact['Recency'])
scoring_data_contact['Recency'] = np.where(((scoring_data_contact['Recency']==20) & (scoring_data_contact['GaveLastYear']==0)), 10, scoring_data_contact['Recency'])

scoring_data_contact['Frequency'] = np.where(((scoring_data_contact['Frequency']==20) & (scoring_data_contact['GaveLastYear']==1)), 1, scoring_data_contact['Frequency'])
scoring_data_contact['Frequency'] = np.where(((scoring_data_contact['Frequency']==20) & (scoring_data_contact['GaveLastYear']==0)), 10, scoring_data_contact['Frequency'])

scoring_data_contact['Seniority'] = np.where(((scoring_data_contact['Seniority']==20) & (scoring_data_contact['GaveLastYear']==1)), 1, scoring_data_contact['Seniority'])
scoring_data_contact['Seniority'] = np.where(((scoring_data_contact['Seniority']==20) & (scoring_data_contact['GaveLastYear']==0)), 10, scoring_data_contact['Seniority'])

scoring_data_contact=scoring_data_contact.join(pd.get_dummies(scoring_data_contact['City'],prefix="City"),how="inner").copy()

scoring_data_contact=scoring_data_contact.join(pd.get_dummies(scoring_data_contact['Education'],prefix="Education"),how="inner").copy()

scoring_data_contact['is_vip'] = np.where(((scoring_data_contact['SeniorList']>0) & (scoring_data_contact['Frequency']>1) & (scoring_data_contact['TotalGift']>100)), 1, 0)

scoring_data_contact['is_active'] = np.where(((scoring_data_contact['Recency']<4) & ((scoring_data_contact['Referrals']>0) | (scoring_data_contact['NbActivities']>0)) & (scoring_data_contact['GaveLastYear']>0)), 1, 0)

scoring_data_contact['is_potential'] = np.where(((scoring_data_contact['Recency'] == 1) & (scoring_data_contact['GaveLastYear']==1) & (scoring_data_contact['Frequency']==1)), 1, 0)

scoring_data_contact['is_new'] = np.where(((scoring_data_contact['GaveLastYear']==0) & (scoring_data_contact['Recency']==10) & (scoring_data_contact['Contact']==1)), 1, 0)

scoring_data_contact['AvgGift'] = scoring_data_contact['TotalGift'] / scoring_data_contact['Frequency']



#scoring_data_contact.head()

X = scoring_data_contact[['Contact', 'is_vip', 'is_active', 'is_potential', 'Woman', 'Salary', 'Age', 'NbActivities', 'Referrals', 'Frequency', 'Recency', 'Seniority', 'GaveLastYear', 'AmtLastYear', 'TotalGift', 'MinGift', 'MaxGift', 'AvgGift', 'City_City', 'City_Downtown', 'City_Rural', 'City_Suburban', 'Education_Elementary', 'Education_High School', 'Education_University / College']] 

regr_predict_contact=DT_model.predict(X)

scoring_data_contact['Prediction'] = regr_predict_contact

scoring_data_contact= scoring_data_contact[['ID','Prediction']]
scoring_data_contact = scoring_data_contact.rename({'Prediction': 'AmtContact'}, axis=1) 
scoring_data_contact.head()

          ID  AmtContact
0  2000001.0   57.737923
1  2000002.0   60.822036
2  2000003.0  133.966029
3  2000004.0   45.584276
4  2000005.0  133.966029

### Predict 'amount given' for members who were not contacted

In [162]:
scoring_data_nocontact = pd.merge(data3, data5, on=["ID"],how="right")

In [136]:
scoring_data_nocontact['GaveLastYear'].value_counts()

0.0    877768
1.0    122232
Name: GaveLastYear, dtype: int64

In [163]:
from pandas.core.accessor import register_dataframe_accessor


# Perform the same strategy for handling missing values for the score dataset.
# In this case, we will only replace missing values of the MinGift variable.

scoring_data_nocontact[['MinGift']] = scoring_data_nocontact[['MinGift']].fillna(value=0)
scoring_data_nocontact[['MaxGift']] = scoring_data_nocontact[['MaxGift']].fillna(value=0)
scoring_data_nocontact[['TotalGift']] = scoring_data_nocontact[['TotalGift']].fillna(value=0)
scoring_data_nocontact[['Frequency']] = scoring_data_nocontact[['Frequency']].fillna(value=20)
scoring_data_nocontact[['Recency']] = scoring_data_nocontact[['Recency']].fillna(value=20)  
scoring_data_nocontact[['Seniority']] = scoring_data_nocontact[['Seniority']].fillna(value=20)

scoring_data_nocontact['MinGift'] = np.where(((scoring_data_nocontact['MinGift']==0) & (scoring_data_nocontact['GaveLastYear']==1)), scoring_data_nocontact['AmtLastYear'], scoring_data_nocontact['MinGift'])
scoring_data_nocontact['MaxGift'] = np.where(((scoring_data_nocontact['MaxGift']==0) & (scoring_data_nocontact['GaveLastYear']==1)), scoring_data_nocontact['AmtLastYear'], scoring_data_nocontact['MaxGift'])
scoring_data_nocontact['TotalGift'] = np.where(((scoring_data_nocontact['TotalGift']==0) & (scoring_data_nocontact['GaveLastYear']==1)), scoring_data_nocontact['AmtLastYear'], scoring_data_nocontact['TotalGift'])

scoring_data_nocontact['Recency'] = np.where(((scoring_data_nocontact['Recency']==20) & (scoring_data_nocontact['GaveLastYear']==1)), 1, scoring_data_nocontact['Recency'])
scoring_data_nocontact['Recency'] = np.where(((scoring_data_nocontact['Recency']==20) & (scoring_data_nocontact['GaveLastYear']==0)), 10, scoring_data_nocontact['Recency'])

scoring_data_nocontact['Frequency'] = np.where(((scoring_data_nocontact['Frequency']==20) & (scoring_data_nocontact['GaveLastYear']==1)), 1, scoring_data_nocontact['Frequency'])
scoring_data_nocontact['Frequency'] = np.where(((scoring_data_nocontact['Frequency']==20) & (scoring_data_nocontact['GaveLastYear']==0)), 10, scoring_data_nocontact['Frequency'])

scoring_data_nocontact['Seniority'] = np.where(((scoring_data_nocontact['Seniority']==20) & (scoring_data_nocontact['GaveLastYear']==1)), 1, scoring_data_nocontact['Seniority'])
scoring_data_nocontact['Seniority'] = np.where(((scoring_data_nocontact['Seniority']==20) & (scoring_data_nocontact['GaveLastYear']==0)), 10, scoring_data_nocontact['Seniority'])

scoring_data_nocontact=scoring_data_nocontact.join(pd.get_dummies(scoring_data_nocontact['City'],prefix="City"),how="inner").copy()

scoring_data_nocontact=scoring_data_nocontact.join(pd.get_dummies(scoring_data_nocontact['Education'],prefix="Education"),how="inner").copy()

scoring_data_nocontact['is_vip'] = np.where(((scoring_data_nocontact['SeniorList']>0) & (scoring_data_nocontact['Frequency']>1) & (scoring_data_nocontact['TotalGift']>100)), 1, 0)

scoring_data_nocontact['is_active'] = np.where(((scoring_data_nocontact['Recency']<4) & ((scoring_data_nocontact['Referrals']>0) | (scoring_data_nocontact['NbActivities']>0)) & (scoring_data_nocontact['GaveLastYear']>0)), 1, 0)

scoring_data_nocontact['is_potential'] = np.where(((scoring_data_nocontact['Recency'] == 1) & (scoring_data_nocontact['GaveLastYear']==1) & (scoring_data_nocontact['Frequency']==1)), 1, 0)

scoring_data_nocontact['is_new'] = np.where(((scoring_data_nocontact['GaveLastYear']==0) & (scoring_data_nocontact['Recency']==10) & (scoring_data_nocontact['Contact']==1)), 1, 0)

scoring_data_nocontact['AvgGift'] = scoring_data_nocontact['TotalGift'] / scoring_data_nocontact['Frequency']

X = scoring_data_nocontact[['Contact', 'is_vip', 'is_active', 'is_potential', 'Woman', 'Salary', 'Age', 'NbActivities', 'Referrals', 'Frequency', 'Recency', 'Seniority', 'GaveLastYear', 'AmtLastYear', 'TotalGift', 'MinGift', 'MaxGift', 'AvgGift', 'City_City', 'City_Downtown', 'City_Rural', 'City_Suburban', 'Education_Elementary', 'Education_High School', 'Education_University / College']] 

regr_predict_nocontact=DT_model.predict(X)

scoring_data_nocontact['Prediction'] = regr_predict_nocontact

scoring_data_nocontact= scoring_data_nocontact[['ID','Prediction']]
scoring_data_nocontact = scoring_data_nocontact.rename({'Prediction': 'AmtNoContact'}, axis=1) 
scoring_data_nocontact.head()

          ID  AmtNoContact
0  2000001.0     57.737923
1  2000002.0     60.822036
2  2000003.0    133.966029
3  2000004.0     45.584276
4  2000005.0    133.966029

In [164]:
result_Amt = pd.merge(scoring_data_contact, scoring_data_nocontact, on=["ID"],how="right")
result_Amt.sort_values(by=['ID'], inplace=True)
result_Amt = result_Amt.astype({'ID':'int'})
result_Amt.head(10)

        ID  AmtContact  AmtNoContact
0  2000001   57.737923     57.737923
1  2000002   60.822036     60.822036
2  2000003  133.966029    133.966029
3  2000004   45.584276     45.584276
4  2000005  133.966029    133.966029
5  2000006   37.870018     37.870018
6  2000007   37.870018     37.870018
7  2000008   57.737923     57.737923
8  2000009   60.822036     60.822036
9  2000010  133.966029    133.966029

## Exporting Results to a CSV File

In [165]:
result_Amt.to_csv('Round2_Output_amt.csv', index=False)

In [ ]:
# Reminder: You are now done with step 1 of Round 2 on predicting the conditional amount.
# Next, to complete Round2, you need to perform step 2 to predict the probability of giving, calculate the uplift and prepare your decision.

In [166]:
!head Round2_Output_amt.csv

ID,AmtContact,AmtNoContact
2000001,57.73792320396367,57.73792320396367
2000002,60.82203648965447,60.82203648965447
2000003,133.9660293298682,133.9660293298682
2000004,45.58427631092375,45.58427631092375
2000005,133.9660293298682,133.9660293298682
2000006,37.870018393623546,37.870018393623546
2000007,37.870018393623546,37.870018393623546
2000008,57.73792320396367,57.73792320396367
2000009,60.82203648965447,60.82203648965447